// Auto-generated by gen_dat_rs.py — do not edit by hand.
pub mod cg1_f2_aa_bulk;
pub mod cg1_f2_vv_bulk;
pub mod cg1_fl_aa_bulk;
pub mod cg1_fl_vv_bulk;
pub mod cg1_x2g1_aa_bulk;
pub mod cg1_x2g1_vv_bulk;
pub mod cq1_f2_aa_bulk;
pub mod cq1_f2_vv_bulk;
pub mod cq1_fl_aa_bulk;
pub mod cq1_fl_vv_bulk;
pub mod cq1_x2g1_aa_bulk;
pub mod cq1_x2g1_vv_bulk;
